"Skills"
enum SkillName {
  attack
  strength
  defence
  ranged
  prayer
  magic
  runecraft
  hitpoints
  crafting
  mining
  smithing
  fishing
  cooking
  firemaking
  woodcutting
  agility
  herblore
  thieving
  fletching
  slayer
  farming
  construction
  hunter
}
