enum SlayerCategory {
  aberrant_spectre
  abyssal_demon
  adamant_dragon
  ankou
  aviansie
  bandit
  banshee
  basilisk
  bat
  bear
  bird
  black_demon
  black_dragon
  black_knight
  bloodveld
  blue_dragon
  boss
  brine_rat
  bronze_dragon
  catablepon
  cave_bug
  cave_crawler
  cave_horror
  cave_kraken
  cave_slime
  chaos_druid
  cockatrice
  cow
  crawling_hand
  crocodile
  dagannoth
  dark_beast
  dark_warrior
  dog
  drake
  dust_devil
  dwarf
  earth_warrior
  elemental
  elves
  fever_spider
  fire_giant
  flesh_crawler
  fossil_island_wyvern
  gargoyle
  ghost
  ghoul
  goblin
  greater_demon
  green_dragon
  harpie_bug_swarm
  hellhound
  hill_giant
  hobgoblin
  hydras
  ice_giant
  ice_warrior
  icefiend
  infernal_mage
  iron_dragon
  jelly
  jungle_horror
  kalphite
  killerwatt
  kurask
  lava_dragon
  lesser_demon
  lizardmen
  lizard
  magic_axe
  mammoth
  minotaur
  mithril_dragon
  mogre
  molanisk
  monkey
  moss_giant
  mutated_zygomite
  nechryael
  ogre
  otherworldly_being
  pirate
  pyrefiend
  rat
  red_dragon
  revenant
  rockslug
  rogue
  rune_dragon
  sand_crab
  scabarite
  scorpion
  sea_snake
  shade
  shadow_warrior
  skeletal_wyvern
  skeleton
  smoke_devil
  sourhog
  spider
  spiritual_creature
  steel_dragon
  suqah
  terror_dog
  troll
  turoth
  tzhaar
  vampyre
  wall_beast
  waterfiend
  werewolf
  wolf
  wyrm
  zombie
}
