# import AttackBonuses from "AttackBonuses.gql"
# import DefenceBonuses from "DefenceBonuses.gql"
# import StrengthBonuses from "StrengthBonuses.gql"

"\"Stats\" provided by equipping the item"
type Bonuses {
  attack: AttackBonuses!
  defence: DefenceBonuses!
  strength: StrengthBonuses!
  prayer: Int!
}
