# import Slot from "Slot.gql"
# import SkillLevel from "SkillLevel.gql"
# import Bonuses from "Bonuses.gql"
# import WeaponAttributes from "WeaponAttributes.gql"

type Equipment {
  slot: Slot!
  requirements: [SkillLevel!]!
  bonuses: Bonuses!
  weapon: WeaponAttributes
}
