# import AlchemyValues from "AlchemyValues.gql"
# import Equipment from "Equipment.gql"

type Item {
  id: Int!
  name: String!
  qualified_name: String!
  members: Boolean!
  examine: String!
  release_date: String!
  weight: Float!
  quest: Boolean!
  stackable: Boolean!
  tradeable: Boolean!
  value: Int!
  alchemy: AlchemyValues
  tradeable_ge: Boolean!
  price: Int
  buy_limit: Int
  icon: String!
  wiki_url: String!
  equipable: Boolean!
  equipment: Equipment
}
