# import Item from "Item.gql"
# import Slot from "./enums/Slot.gql"
# import WeaponCategory from "WeaponCategory.gql"

type Query {
  items(
    nameLike: String
    qualifiedNameLike: String
    slot: Slot
    members: Boolean
    quest: Boolean
    stackable: Boolean
    tradeable: Boolean
    tradeable_ge: Boolean
    equipable: Boolean
    limit: Int
  ): [Item!]!
  item(id: Int): Item
  weaponCategory(name: String): WeaponCategory
}
