# import SlayerMaster from "./enums/SlayerMaster.gql"
# import SlayerCategory from "./enums/SlayerCategory.gql"

type SlayerInfo {
  "Slayer masters that can assign this monster"
  masters: [SlayerMaster!]!
  "Slayer level required"
  level: Int!
  "Slayer xp granted on kill"
  xp: Float!
  "Slayer task categories this monster can be killed for"
  categories: [SlayerCategory!]!
}
